structure: multiple-files # "multiple-files", "single-file"
bloomFilter:
  precision: 0.01
cache:
  size: 10
skipList:
  maxLevel: 7
lsm:
  maxLevel: 5
tokenBucket:
  size: 10
  rate: 1000
memtable:
  threshold: 50
  size: 120
  use: skip-list #skip-list, b-tree